### ISSUE TITLE
[Feature Request] tab preview locates on the right side of tab list

### ISSUE THREAD

**Issue by Schroedingersdoraemon** [Bill13579/tabby#65]
HI, Bill13579

Some users might prefer to put the tabby icon on the upper left corner. Therefore if I want to open a tab, to move the mouse cursor diagonally costs a little bit more calories than to move directly downward .

![2020-11-29_17-20](https://user-images.githubusercontent.com/43810289/100538065-6789be00-3268-11eb-9d5a-ba4291431ee9.png)

As indicated in the image, I'm wondering if you could please add a feature which determines the preview location in the options? That is, tab list is on the left and preview window is on the right. 

Thanks a lot and much appreciated

**Comment by Bill13579** [comment]
Add the following snippet into the custom theme section of the settings page (v3.0.0):

```css
:root {
    --bg: #ffffff;
    --bg-lite: #dfdfdf;
    --bg-indented: #f2f2f2;
    --bg-indented-0: rgb(227, 227, 227);
    --bg-indented-translucent: rgba(250, 250, 250, 0.1);
    --bg-indented-2: #5e5e5e;
    --bg-indented-3: #fff;
    --fg-lite: #000000;
    --fg: #191919;
    --fg-shadow: #606060;
    --fg-shadow-2: #aaaaaa;
    --fg-label: #000000;
    --fg-user-content: #000000;

    --input-border: #dadada;
    --input-focus: #91c3ec;
    --btn-inline-text: rgb(0, 153, 255);
    --current-window: #3592fc;
    --current-tab: #b6d2ff;
    --selected: #dce9ff;
    --btn-inline-text-hover: #0062ff;
    --selected-2: #dce9ff;

    --input-focus90: #e791ec; /*currently unused*/
    --input-focus90t: #ea4af260; /*currently unused*/
    --btn-inline-text90: #e500ff; /*currently unused*/
    --current-window90: rgb(173, 0, 173);
    --current-tab90: rgb(255, 151, 255);
    --selected90: rgb(255, 125, 255);
    --btn-inline-text-hover90: rgb(173, 0, 173);
    --btn-inline-text2-hover90: rgb(128, 0, 128);
    --selected90-2: rgb(255, 125, 255);

    --save: #aeffc2;
    --load: #8bf1ff;

    --svg-filter: invert(0%) sepia(100%) saturate(0%) hue-rotate(99deg) brightness(95%) contrast(104%); /* generate here: https://codepen.io/sosuke/pen/Pjoqqp */
    --svg-filter-white: invert(100%) sepia(5%) saturate(0%) hue-rotate(289deg) brightness(104%) contrast(107%);
}
:root .window-entry .single-controls .-force-filter-svg-to-match-theme {
    filter: none;
}
#main #details-placeholder, #main #details-pane {
    grid-column-start: 2;
    grid-row-start: 1;
    padding-left: 0;
    padding-right: calc(16.75px * var(--scale));
    transition: none;
}
#main #session-display-pane {
    grid-column-start: 1;
    grid-row-start: 1;
    padding-right: 0;
    padding-left: calc(10.25px * var(--scale));
    transition: none;
}
```

Hope it helps :)
