### ISSUE TITLE
[Feature Request] Amount of Tabs Found in Search Filter

### ISSUE THREAD

**Issue by madmuffinz** [Bill13579/tabby#67]
Sometimes I have a lot of tabs that fall under a similar search term and I am curious about how many tabs there are when the list is too long
Something like "[amount of tabs filtered] Tabs Found" for the Tab Search?

**Comment by Bill13579** [comment]
Hey @madmuffinz, paste the following into the custom theme section in the new update:

```css
:root {
    --bg: #ffffff;
    --bg-lite: #dfdfdf;
    --bg-indented: #f2f2f2;
    --bg-indented-0: rgb(227, 227, 227);
    --bg-indented-translucent: rgba(250, 250, 250, 0.1);
    --bg-indented-2: #5e5e5e;
    --bg-indented-3: #fff;
    --fg-lite: #000000;
    --fg: #191919;
    --fg-shadow: #606060;
    --fg-shadow-2: #aaaaaa;
    --fg-label: #000000;
    --fg-user-content: #000000;

    --input-border: #dadada;
    --input-focus: #91c3ec;
    --btn-inline-text: rgb(0, 153, 255);
    --current-window: #3592fc;
    --current-tab: #b6d2ff;
    --selected: #dce9ff;
    --btn-inline-text-hover: #0062ff;
    --selected-2: #dce9ff;

    --input-focus90: #e791ec; /*currently unused*/
    --input-focus90t: #ea4af260; /*currently unused*/
    --btn-inline-text90: #e500ff; /*currently unused*/
    --current-window90: rgb(173, 0, 173);
    --current-tab90: rgb(255, 151, 255);
    --selected90: rgb(255, 125, 255);
    --btn-inline-text-hover90: rgb(173, 0, 173);
    --btn-inline-text2-hover90: rgb(128, 0, 128);
    --selected90-2: rgb(255, 125, 255);

    --save: #aeffc2;
    --load: #8bf1ff;

    --svg-filter: invert(0%) sepia(100%) saturate(0%) hue-rotate(99deg) brightness(95%) contrast(104%); /* generate here: https://codepen.io/sosuke/pen/Pjoqqp */
    --svg-filter-white: invert(100%) sepia(5%) saturate(0%) hue-rotate(289deg) brightness(104%) contrast(107%);
}
:root .window-entry .single-controls .-force-filter-svg-to-match-theme {
    filter: none;
}
#where-to-put-the-tab-list {
    counter-reset: matching-entries;
}
#where-to-put-the-tab-list .tab-entry:not(.-tui-list-hidden--filter) {
    counter-increment: matching-entries;
}
#where-to-put-the-tab-list .tab-entry:last-child {
    display: block !important;
    pointer-events: none;
    height: 0;
    padding: 0;
}
#where-to-put-the-tab-list .tab-entry:last-child * {
    opacity: 0;
}
#where-to-put-the-tab-list .tab-entry:last-child:after {
    content: counter(matching-entries) " Tabs Found";
    position: fixed;
    top: 22px;
    left: 36%;
    opacity: 1;
    font-size: 14px;
    color: #5e5e5e;
    text-align: right;
}
```

Hope it helps :D
